language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"
  # PyPy versions
#  - "pypy3.5"

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - pip install -r requirements-dev.txt
  - pip install .

before_script:
  - ./cc-test-reporter before-build

script:
  - zmei build
  - pytest --cov=zmei_generator/

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

#after_success:
#  - codecov

deploy:
  provider: pypi
  user: ribozz
  password:
    secure: "olyXpme/ZCWEct5ZquGFHL6RA2u71os+bAuGzhue7VqasWGuQL2zJilzFe66iv12E96S8RH4eyjdTLrTaH0lXIPM1lL3HqMjIwl18ENTg90swspFG6PSSSybIw/TkVwrqRsRqyPjW99LCOJPsKGtz4vkLl0cCkDDdy12vl3mrs0YhuQv8YKVbY1vwmyg8Yzcy/7P9hUl85AT2R2uFbDIoAPLIFq1AV+HKGfXamlnvaHdEtXgfREMBgqovMpApyaR6xXA2KA35xZTGkl1+oDhlNpmqy8lr1cc4txJBZq+GTMrTyCbM0cDE1dWAanHy98RApkEJ1bViAdTfHXIuB4pgshvINE5Iv6Rl3jAtATEHufhL/o5wxAffFbUnxC7u5K/y+OFAYWOcYrzkmOfTdul1WuodPQK15uvTKxELdTH5Pkat5oAlCrWx4ndSOD6s9xcu4LRDAN1dBpZhKFxrMcMX+TL+J/V9+2h8vQLrb1/vCY2pcMk2CgxDC1KSNR1U24PGlTSPcd7QJVMP19gulvWWpmse7nqZ7aka2J/clwmJYUtb1WgNoOVGJnl3FgH3zUuBJ8U2XBl4fWTXM+ZPop86Weijx/ED+Rg2Al65YIFK/d81EOnX8IFYwZ2ysSGgvcX88FUkOJ6Srp1PPlcCMBhXHPDVZxRjTcPX2f/lc8/+nY="
  on:
    tags: true